CREATE TABLE IF NOT EXISTS job_logs
(
    id BIGINT AUTO_INCREMENT PRIMARY KEY KEY,
    filename VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);